# Generated by Django 3.2.15 on 2022-09-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220910_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='news_day',
            field=models.BooleanField(blank=True, verbose_name='Новость дня'),
        ),
    ]
