# Generated by Django 3.2.15 on 2022-09-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_news_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlatformStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.IntegerField(default=0, verbose_name='Пользователи Windows')),
                ('mac', models.IntegerField(default=0, verbose_name='Пользователи Windows')),
                ('iphone', models.IntegerField(default=0, verbose_name='Пользователи Windows')),
                ('android', models.IntegerField(default=0, verbose_name='Пользователи Windows')),
                ('other', models.IntegerField(default=0, verbose_name='Пользователи Windows')),
            ],
        ),
    ]
