# Generated by Django 3.2.15 on 2022-10-02 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_userplatformstats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userplatformstats',
            options={'verbose_name_plural': 'СтатистикаПО'},
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='news_day',
            field=models.BooleanField(default=True, verbose_name='Новость дня'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.Tag', verbose_name='Тэги постов'),
        ),
    ]
