# Generated by Django 3.2.15 on 2022-10-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20221002_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='news_day',
            field=models.BooleanField(blank=True, verbose_name='Новость дня'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
