# Generated by Django 3.2.15 on 2022-10-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20221002_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='news_day',
            field=models.BooleanField(default=False, verbose_name='Новость дня'),
        ),
    ]
